apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: creator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - acid.zalan.do
    resources:
      - postgresqls
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: creator
subjects:
  - kind: ServiceAccount
    name: build-robot
